---
abstract: 'Release your dist to a Pinto repository'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ReleaseToPinto
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Dist::Zilla::Plugin::ReleaseToPinto:
    file: lib/Dist/Zilla/Plugin/ReleaseToPinto.pm
    version: 0.003
requires:
  Class::Load: 0
  Dist::Zilla::Role::Releaser: 0
  English: 0
  Moose: 0
  MooseX::Types::Moose: 0
  Pinto::Types: 0
  perl: 5.006
resources:
  homepage: https://github.com/thaljef/Dist-Zilla-Plugin-ReleaseToPinto
  repository: https://github.com/thaljef/Dist-Zilla-Plugin-ReleaseToPinto
version: 0.003
